[package]
name = "rust-kafka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://docs.rs/kafka/latest/kafka/
kafka = "0.9.0" 
